/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aaron' at '30/05/18 12:14' with Gradle 2.14
 *
 * @author aaron, @date 30/05/18 12:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
